name: Generate ASCII artwork

on:
    schedule:
      - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Chekcout Repo
          uses: actions/checkout@v6
        - name: install Cowsay program
          run: |
            sudo apt-get install cowsay -y
            cowsay -f tux "Linux rules the servers, tux!" >> tux.txt
            ls -ltra
            grep -i "tux" tux.txt
            cat tux.txt
    ascii_job2:
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - name: List files
          run: pwd
        
        # - name: List files
        #   run: ls

        # - name: Read files
        #   run: cat README.md
